"""
01_documents.py
Knowledge base: 19 real dental patient-education handouts (self-collected).

Metadata schema (Lab 8 / Lab 9): document_id, title, doc_type, effective_date,
is_current, text. Two topics carry an OUTDATED + CURRENT pair to demonstrate
current-vs-outdated conflict resolution downstream:
  - crown_bridge_care : D1 (2021, outdated)  ->  D9 (2025, current)
  - periodontal_scaling: D2 (2020, outdated) -> D12 (2025, current)
"""

DOCUMENTS = [{'document_id': 'D1',
  'title': 'Post-Operative Instructions for Crown or Bridges',
  'doc_type': 'crown_bridge_care',
  'effective_date': '2021-04-01',
  'is_current': False,
  'text': 'Post-Operative Instructions for Crown or Bridges\n'
          'Congratulations! You now have you final restoration which is permanent. Please\n'
          'remember that your new crown or bridge, as well as the rest of your natural teeth, '
          'need\n'
          'regular maintenance with your doctor and hygienist. This is the only way to keep them\n'
          'healthy.\n'
          'Routine cleaning and maintenance appointments are recommended every 3 to 6\n'
          'months, depending on the condition of your gums. Please make an appointment if you\n'
          'have not already done so.\n'
          '- Your gums may have become sore during this procedure. Please rinse with warm\n'
          'salt water a few times daily. Flossing is very important to help heal the area. Even\n'
          'if it is sore, please attempt to floss daily, as this will help it to heal.\n'
          '- Bridges need floss threaders. Threaders allow you to floss below the bridge\n'
          'properly. We will show you how to use them at your final appointment. Threaders\n'
          'may be purchased at any drug store.\n'
          '- If a permanent crown or bridge feels "high" or like you are hitting that tooth '
          'first,\n'
          'please call the office to have it adjusted. This restoration WILL NOT adjust itself\n'
          'like a temporary might. Without correction you will have a toothache and/or a\n'
          'sore jaw.\n'
          '- Avoid chewing sticky, chewy foods, and chewing gum for 24-hours.'},
 {'document_id': 'D2',
  'title': 'Root Planing and Scaling for Gum Disease',
  'doc_type': 'periodontal_scaling',
  'effective_date': '2020-09-01',
  'is_current': False,
  'text': 'Root Planning and Scaling for Gum Disease\n'
          'Root planning and scaling is one of the most effective ways to treat gum disease before '
          'it\n'
          'becomes severe. Root planing\n'
          'and scaling cleans between the gums and the teeth down to the roots. Your dentist may\n'
          'need to use a local anesthetic to\n'
          'numb your gums and the roots of your teeth.\n'
          'The Drs. may place antibiotic fibers into the pockets between your teeth and gums. The\n'
          'antibiotic will he help speed\n'
          'healing and prevent infection.\n'
          'What to Expect After Treatment?\n'
          'If anesthesia is used, your lips and gums may remain numb for a few hours. Planing and\n'
          'scaling causes little to no\n'
          'discomfort.\n'
          'Why It Is Done?\n'
          'Root planing and scaling is done when gums have either started to pull away from the '
          'teeth\n'
          'or the roots of the teeth have\n'
          'hard mineral deposits (tartar) on them.\n'
          'How Well It Works?\n'
          'If you maintain good dental care after the procedure, the progression of gum disease\n'
          'should stop: And your gums will heal\n'
          'and become firm and pink again.\n'
          'Risk?\n'
          'Root planing and scaling can introduce harmful bacteria into the bloodstream. Gum '
          'tissue\n'
          'is also at risk of infection. You\n'
          'may need to take antibiotics before and after surgery if you have a condition that puts '
          'you\n'
          'at high risk for a severe\n'
          'infection of if infections are particularly dangerous for you. You may need to take\n'
          'antibiotics if you:\n'
          'Have certain heart problems that make it dangerous for you to get a heart infection '
          'called\n'
          'endocarditis.\n'
          'Have an impaired immune system\n'
          'Had recent major surgeries or have man-made body parts, such as an artificial hip or '
          'heart\n'
          'valve.\n'
          'What to Think About?\n'
          'Root planing and scaling is a simple procedure that can work very well to stop gum\n'
          'disease.\n'
          'Brush and floss regularly afterward. Without proper dental care, your gum disease may\n'
          'progress.\n'
          'To promote healing, stop all use of tobacco. Smoking or using spit tobacco reduces '
          'your\n'
          'ability to fight infection\n'
          'of your gums and delays healing.\n'
          'Further prolonging treatment can result in loss of teeth, server pain, infection, as '
          'well as\n'
          'additional cost in dental\n'
          'treatment.'},
 {'document_id': 'D3',
  'title': 'Post-Operative Instructions Following Oral Surgery',
  'doc_type': 'oral_surgery_general',
  'effective_date': '2025-01-10',
  'is_current': True,
  'text': 'Post-Operative Instructions Following Oral Surgery\n'
          'Gauze has been placed into the extraction area to allow you to apply pressure and '
          'prevent\n'
          'excessive bleeding. You should bite onto gauze for 30 minutes, after this time has '
          'passed\n'
          'remove the gauze and if the site is still bleeding replace with new gauze for another '
          '30\n'
          'minutes. If this does not allow the bleeding to subside you can try biting onto a damp '
          'tea\n'
          'bag (the acids in the tea bag have a clotting effect). Do not agitate the area by '
          'removing and\n'
          'replacing the gauze often, this can cause the site to bleed excessively.\n'
          'Some patients will receive sutures in the area of the extraction/surgery site to assist '
          'with\n'
          'healing. If you have sutures the assistant will advise you if they are dissolvable or '
          'if you will\n'
          'require an appointment to have your non-dissolvable sutures removed.\n'
          'It is possible that you may have some swelling and bruising in the general area of the\n'
          'extraction/surgery site. This will usually reach its peak on day 2 or 3 after surgery. '
          'It will\n'
          'gradually disappear and is of no cause for major concern unless the swelling is '
          'obstructing\n'
          'your airway. To treat the swelling, you will apply an ice pack wrapped in a towel for '
          '10\n'
          'minutes on and 10 minutes off for up to two (2) hours at a time.\n'
          'Additional Instructions\n'
          '- Smoking should be avoided for the first 48 hours to avoid getting a dry socket.\n'
          '- Do not use a Straw to drink for the first 48 hours.\n'
          '- Do not spit forcefully as this may dislodge the clot that is protecting your\n'
          'extraction/surgery site.\n'
          '- Do not participate in any strenuous physical activity for a minimum of 24 hours '
          'after\n'
          'surgery.\n'
          '- If you have had a tooth extracted from the upper, refrain from blowing your nose for\n'
          'the first 48 hours.\n'
          '- Keep your fingers, tongue and toothbrush away from the extraction/surgery site.\n'
          '- Do not rinse your mouth for the first 24 hours, mouthwashes like Scope or Listerine\n'
          'should be avoided until the area has healed in 24 hours you will begin frequently and\n'
          'gently rinsing with a warm salt water. (2tsp Salt dissolved into 8oz of water)\n'
          '- You may have cold or lukewarm but not HOT liquids for the first 4-6 hours following\n'
          'surgery, after this time you may incorporate soft foods. Do not drink any carbonated\n'
          'beverages for the first 48 hours to prevent dislodging the clot that is protecting the\n'
          'site. Also avoid crunchy foods that may cause particles to lodge into the\n'
          'extraction/surgical site.'},
 {'document_id': 'D4',
  'title': 'Post-op Instructions for Implants and Extractions',
  'doc_type': 'implant_extraction_general',
  'effective_date': '2025-02-05',
  'is_current': True,
  'text': 'Post-op Instructions for Implants and Extractions\n'
          'WHEN SHOULD YOU NOTIFY THE DOCTOR\n'
          '1. If profuse bleeding continues after 3-4 hours of applied pressure.\n'
          '2. If you are unable to maintain a nutritious diet after 48hours.\n'
          '3. If the pain and/or swelling increases after the third day.\n'
          '4. If an oral bandage becomes dislodged prior to the third day.\n'
          '5. If you have an allergic reaction to medications such as: a. Skin rash b. Hives c.\n'
          'Elevated temperature d. Increased and/or erratic heart rate e. Nausea/vomiting f.\n'
          'Dizziness/fainting g. Blurred vision\n'
          'GENERAL INSTRUCTIONS\n'
          '- DO NOT rinse for at least 24hours after the surgery\n'
          '- DO NOT exercise or do heavy lifting for 3 to 5days after surgery\n'
          '- DO NOT smoke for at least 72 hours\n'
          'WHAT TO EXPECT FOLLOWING ANY SURGERY\n'
          'BLEEDING To slow or prevent bleeding, bite with light pressure on the gauze pack that '
          'has\n'
          'been placed over the surgical area. Pressure should be applied in 20 to 30 minute '
          'intervals\n'
          'and repeated until the bleeding is brought under control. If bleeding persists without\n'
          'slowing for several hours, apply a gauze soaked in strong tea and repeat the above '
          'steps\n'
          'until the bleeding stops. Exercising and heavy lifting will raise your blood pressure '
          'and will\n'
          'dislodge the blood clot and bleeding will resume. Avoid exercising for 3 to 5 days '
          'following\n'
          'surgery.\n'
          'SWELLING To prevent and/or minimize swelling, apply ice packs at 10minute intervals to\n'
          'the surgical area. After 72 hours, apply warm compresses to the area to relieve '
          'swelling.\n'
          'Swelling is a natural part of the healing process and can be expected for 3days to '
          'several\n'
          'weeks depending on the nature and the extent of the surgery.\n'
          'DISCOMFORT Following most surgical procedures there may or may not be pain,\n'
          'depending on your threshold for pain. You will be provided with medication for '
          'discomfort\n'
          'that is appropriate for you. In most cases, a non-narcotic pain regimen will be given\n'
          'consisting of Acetaminophen (Tylenol) & Ibuprofen (Motrin). These two medications, '
          'taken\n'
          'together, will be as effective as a narcotic without any of the side effects associated '
          'with\n'
          'narcotics. If a narcotic has been prescribed, follow the directions carefully. If you '
          'have any\n'
          'questions about these medications interacting with other medications you are presently\n'
          'taking, please call our office first, your physician and/or your pharmacist.'},
 {'document_id': 'D5',
  'title': 'Post-Operative Instructions for Root Canal Treatment',
  'doc_type': 'root_canal',
  'effective_date': '2025-03-01',
  'is_current': True,
  'text': 'Post-Operative Instructions for Root Canal Treatment\n'
          'Endodontic, or root canal, treatment is now complete. The canals inside the roots have\n'
          'been cleaned, irrigated, medicated, and permanently sealed. The opening in the tooth '
          'with\n'
          'the root canal treatment has been sealed with a filling.\n'
          'Delay in obtaining the final restoration (crown) on this tooth may result in the '
          'fracture\n'
          'and/or possible loss of this tooth.\n'
          'What to expect:\n'
          '- It is NOT uncommon for a tooth to be uncomfortable or even exhibit a dull ache\n'
          'immediately after receiving root canal therapy. This should subside within a few\n'
          'days or weeks. This occurs because of conditions, which exist before treatment was\n'
          'started. Experience shows that if there was pain prior to treatment, there may be\n'
          'some degree of pain that will continue following the treatment. Remember that pain\n'
          'radiates. You may feel discomfort in other teeth in the area. This can be created by\n'
          'inflammation and/or increase in blood volume to occur in the healing process.\n'
          '- Your tooth will be sensitive to biting pressure and may even appear to feel loose.\n'
          'This feeling is a result of the nerve ending just outside the end of the root of the\n'
          'treated tooth. Discomfort in the area for a few days to weeks is common. Warm salt\n'
          'water rinses for the next two days will help. Try to avoid chewing on this area until\n'
          'the tenderness has subsided.\n'
          '- Occasionally a small "bubble" or "pimple" will appear on the gum tissue within a few\n'
          'days after completion of a root canal. This is a release of pressure and bacteria\n'
          'which is no longer sustained around the tooth. This should disappear within a few\n'
          'days.\n'
          '- The office staff will review with you the timeline and steps needed to complete the\n'
          'final restoration (crown) for this tooth.'},
 {'document_id': 'D6',
  'title': 'Opalescence Take-Home Whitening Step-by-Step Instructions',
  'doc_type': 'whitening_take_home_opalescence',
  'effective_date': '2025-04-01',
  'is_current': True,
  'text': 'Opalescence Step-by-Step Instructions\n'
          'Step 1: Spread gel into your custom bleaching tray/retainer using a maximum of '
          'one-half\n'
          '(1/2) to one-third (1/3) of a syringe.\n'
          'Step 2: Brush your teeth, and then insert both trays (top and bottom) onto your teeth.\n'
          'Optionally you can do the process with one tray at a time or alternate treatments '
          'between\n'
          'the top and bottom.\n'
          'Any excess gel that overflows from the tray onto the gums should be removed with a '
          'cotton\n'
          'ball, tissue, soft toothbrush, or clean finger. This is important because prolonged '
          'exposure\n'
          'to the gums can cause significant irritation.\n'
          'Opalescence instructions state that this process can be repeated every day for the\n'
          'duration of the treatment but we recommend at least every-other day to reduce pain and\n'
          'sensitivity by giving your teeth and gums time to recover. There is really no rush and '
          'spacing\n'
          'out the treatment will provide greater comfort without and negative effects.\n'
          'Step 3: For Opalescence 20%, remove the tray after 2 to 4 hours during the day and '
          'only\n'
          'consider overnight treatment if your teeth can tolerate the 20% concentration well.\n'
          'Although the standard Opalescence instructions do not include this, based on customer\n'
          'feedback, we do not recommend an overnight exposure for the first few treatments until\n'
          'you have tried shorter durations and found that your tooth and gum sensitivity is '
          'tolerable.\n'
          'Step 4: After removing the trays, brush your teeth normally. Then rinse the trays in '
          'cool\n'
          'water (note that hot water can warp or distort certain types of bleaching trays) and '
          'store\n'
          'them in a cool place out of the sun.\n'
          'Length of Treatment\n'
          'This is a common question: how long should you continue to use Opalescence. In fact\n'
          'there is nothing in the Opalescence instructions about the duration. Your dentist '
          'might\n'
          'have come up with an estimate but really it is up to you. If the whitening gel is '
          'working for\n'
          'you, as long as the sensitivity or irritation are tolerable or negligible, you can use '
          'this\n'
          'product until you achieve the desired whiteness. In short, here is the only '
          'Opalescence\n'
          'instructions we can give on duration: continue to use it until you achieve the desired\n'
          'results.\n'
          'After you have completed the treatment, you will probably want to do a touch-up '
          'treatment\n'
          'every so often to maintain your pearly whites. For example, once every 6 months you '
          'might\n'
          'want to resume the treatment for several days but again. However, there are no\n'
          "Opalescence instructions on this point; everyone's teeth are different due to many "
          'factors\n'
          'so it is up to you and/or your dentist to find how Opalescence works best for you.'},
 {'document_id': 'D7',
  'title': 'Post-Operative Instructions After Bone Graft Surgery',
  'doc_type': 'bone_graft',
  'effective_date': '2025-01-20',
  'is_current': True,
  'text': 'BONE GRAFT\n'
          '- MOST IMPORTANT DIRECTION: You have been given an IRRIGATION SYRINGE and\n'
          'instructed how and when to use it. You may begin gentle rinsing with IRRIGATION\n'
          'SYRINGE using a saltwater solution (1 or 2 teaspoon salt + 8 ounces warm water).\n'
          'Be sure to RINSE AFTER EACH MEAL OR SNACK, or every 2-3 hours! Refill you\n'
          'syringe 2-3 times and rinse gently until no more food is seating at the site. If you\n'
          'keep your surgical site clean, you will heal, if you do not, it will cause secondary\n'
          'infection. Remember, it takes only one time for food to get into the surgical site and\n'
          'then secondary infection will start, so be sure to RINSE AFTER EACH MEAL OR\n'
          'SNACK!\n'
          '- CHLORHEXIDINE RINSING: In addition to warm salt water rinses, you would also\n'
          'need to rinse with “liquid antibiotic” called Chlorhexidine. If you been given\n'
          'prescription at your appointment, then follow these instructions. After breakfast\n'
          'and dinner, or morning and evening, when you rinse with warm salt water and get\n'
          'the site cleaned, now you need to rinse with Chlorhexidine, use same syringe and do\n'
          'exactly the same step as with warm salt water, but now use Chlorhexidine.\n'
          '- ANTIBIOTICS: Take all of them as PRESCRIBED AND DIRECTED to you until you\n'
          'finish all of your antibiotics. Women: some antibiotics can reduce the effectiveness\n'
          'of birth control pills. Use alternate birth control methods for two months.\n'
          '- PAIN: Some discomfort is normal after surgery. To minimize pain, take Tylenol,\n'
          'Motrin or Advil, or similar non-aspirin pain reliever to maintain comfort. Start take '
          'it\n'
          'before the anesthesia wears off. If prescription pain medication is prescribed, take '
          'it\n'
          'as instructed on the label. Don’t exceed the dose on the label. Taking it with food\n'
          'will help reduce upset stomach. Avoid driving or operating heavy machinery when\n'
          'taking pain prescriptions. Do not drink alcohol while taking prescription pain\n'
          'medications. Strong pain medications, like Norco, must be only taken before\n'
          'bedtime.\n'
          '- DO NOT: Swish, suck through a straw, spit or smoke, it can all dislodge the clot.\n'
          'Keep anything sharp from entering the wound (crunchy food, toothpicks, eating\n'
          'utensils). Be sure to chew on the opposite side until the area heals\n'
          'completely. Understand that any food caught inside the extraction socket (place\n'
          'where tooth used to be) can cause infection, pain and additional surgery, so stay on\n'
          'soft or liquid food diet and give your body enough time to heal, BUT BE SURE TO\n'
          'RINSE AFTER EACH MEAL OR SNACK!\n'
          '- BLEEDING: When you leave the office, you might be biting on a gauze pad to control\n'
          'bleeding. Keep slight pressure on this gauze for at least 30 to 60 minutes. Don’t\n'
          'change it during this time; it needs to remain undisturbed while a clot forms in the\n'
          'extraction socket. After 30 minutes you may remove it. You may bite on another\n'
          'gauze or a tea bag for another 30 minutes if you feel it is still bleeding. Small\n'
          'amounts of blood in the saliva can make your saliva appear quite red. This is normal\n'
          'and may be noticed the rest of the day after the procedure.\n'
          '- DIET: Eat soft foods until the area is healed. Maintain a good, balanced diet, you\n'
          'need proper nutrition to heal. Drink plenty of water. Avoid alcohol for 48\n'
          'hours. Keeping the area clean from food debris will promote good healing.\n'
          '- SMOKING: Smoking should be stopped following surgery. Healing and success of\n'
          'the surgery will be substantially reduced by the cigarette smoke chemicals in your\n'
          'body. Also the suction created when inhaling cigarettes can dislodge the clot.\n'
          'Smokers are at greater risk of developing a painful condition called “Dry Socket”,\n'
          'which can hurt worse then a toothache and there is no cure for it. You must quit for\n'
          'at least 5 day to allow initial healing.\n'
          '- NAUSEA: This is most often caused by taking pain medications on an empty\n'
          'stomach. Reduce nausea by preceding each pain pill with soft food, and taking the\n'
          'pill with a large glass of water.\n'
          '- SWELLING: Applying an ice bag to the face over the operated area will minimize\n'
          'swelling. Apply for 15 minutes, then remove for 15 minutes. Continue this for the\n'
          'first day.\n'
          '- NUMBNESS: The local anesthetic will cause you to be numb for several hours after\n'
          'you leave the office. Be very careful not to bite, chew, pinch, or scratch the numb\n'
          'area. Sometimes the extraction causes residual numbness or tingling for six weeks\n'
          'or longer. Contact our office if you experience these symptoms.\n'
          '- BRUSHING: Do not brush your teeth for the first 8 hours after surgery. After this, '
          'you\n'
          'must brush your teeth to reduce bacteria amount, but avoid the area of surgery for\n'
          'few days.\n'
          '- ACTIVITY: After leaving the office, rest and avoid strenuous activities for the\n'
          'remainder of the day. Keeping blood pressure lower will reduce bleeding and aid\n'
          'healing.\n'
          '- SINUS: If your sinus was involved in the procedure, you should avoid blowing your\n'
          'nose or playing a wind musical instrument for one week. Use of decongestant\n'
          'medications might be recommended.\n'
          '- SUTURES: If you had resorbable sutures placed, then they will dissolve on its own\n'
          'in 7-10 days and you do not need to worry about suture removal. If you have sutures\n'
          'that do not resorb, then you need to return back to the office for a sutures removal.\n'
          '- SPECIAL CONSIDERATIONS – Trismus (stiffness) in the face muscles may cause\n'
          'difficulty in opening your mouth for a period of days. Moist heat compresses can\n'
          'minimize this condition. You may experience aching from other teeth. This\n'
          'discomfort is caused by referred pain and is a temporary condition. It is not unusual\n'
          'to develop bruising in the area of the extraction. There may be a slight elevation in\n'
          'temperature for 24-48 hours. If the fever persists, please contact our office.\n'
          '- FOLLOW-UP APPOINTMENTS: You WILL NEED TO RETURN to the office for a brief\n'
          'follow-up healing check.\n'
          'Following these instructions very closely will greatly help your comfort, and promote\n'
          'uneventful healing of the area. If any of the instructions are not followed, you might '
          'have\n'
          'significantly more discomfort, and the success of the procedure may be affected.'},
 {'document_id': 'D8',
  'title': 'Brushing With a Disclosing Agent (Home Hygiene Guide)',
  'doc_type': 'home_hygiene_technique',
  'effective_date': '2025-05-01',
  'is_current': True,
  'text': 'BRUSHING\n'
          'Brushing your teeth with a disclosing agent can be a great way to visualize areas you '
          'might\n'
          "be missing during your regular routine. Here's how to do it effectively and safely:\n"
          'Before you begin:\n'
          "- Gather your supplies: You'll need your regular toothbrush, toothpaste, a disclosing\n"
          'tablet or rinse (click here for list of products on Amazon), and a glass of water.\n'
          "- Choose your lighting: Good lighting is key for seeing the disclosing agent's "
          'effects.\n'
          'Natural daylight or a well-lit bathroom are ideal.\n'
          'Brushing with the disclosing agent:\n'
          '1. Brush as usual: Start by brushing your teeth with your regular toothpaste for 2\n'
          'minutes, focusing on all surfaces of each tooth.\n'
          '2. Use the disclosing agent: After rinsing with water, chew the disclosing tablet or\n'
          'swish the rinse in your mouth for 30 seconds, coating all your teeth.\n'
          '3. Rinse lightly: Rinse with a small amount of water, leaving some of the disclosing\n'
          'agent on your teeth. This will highlight areas you missed brushing.\n'
          'Analyzing the results:\n'
          '- Look for stained areas: The disclosing agent will stain areas where plaque and food\n'
          'debris remain, appearing as pink, red, or purple spots.\n'
          '- Focus on missed areas: Pay particular attention to the gum line, behind teeth, and\n'
          'in between molars, where plaque often builds up.\n'
          '- Refine your brushing: Use your toothbrush to carefully remove the stained areas,\n'
          'focusing on gentle circular motions and short back-and-forth strokes.\n'
          'Additional tips:\n'
          "- Don't swallow the disclosing agent: It's meant for temporary staining, not\n"
          'ingestion.\n'
          '- Rinse thoroughly after: Remove all traces of the disclosing agent with water to\n'
          'avoid staining your tongue or lips.\n'
          '- Brush regularly: Using a disclosing agent once or twice a week can help you\n'
          'develop good brushing habits and maintain optimal oral hygiene.\n'
          'Remember, even with good brushing, plaque and tartar can build up over time, so '
          'regular\n'
          'dental cleanings are still essential for maintaining healthy teeth and gums.'},
 {'document_id': 'D9',
  'title': 'Crown or Bridge Post-Operative Care (Updated)',
  'doc_type': 'crown_bridge_care',
  'effective_date': '2025-08-01',
  'is_current': True,
  'text': 'CROWN OR BRIDGE\n'
          '- DO NOT DISTURB THE AREA: For the next few days, and especially the first 24\n'
          'hours, it is very important to allow your body to form a good clot and start natural\n'
          'healing process.\n'
          '- DO NOT: Swish, suck through a straw, spit or smoke, it can all dislodge the\n'
          'clot. Keep anything sharp from entering the wound (crunchy food, toothpicks, eating\n'
          'utensils).\n'
          '- Be sure to chew on the opposite side until the area heals completely.\n'
          '- Understand that any food caught inside the extraction socket (place where tooth\n'
          'used to be) can cause infection, pain and additional surgery, so stay on soft or '
          'liquid\n'
          'food diet and give your body enough time to heal.\n'
          '- MOST IMPORTANT DIRECTION: You have been given an IRRIGATION SYRINGE and\n'
          'instructed how and when to use it. You may begin gentle rinsing with IRRIGATION\n'
          'SYRINGE using a saltwater solution (1 or 2 teaspoon salt + 8 ounces warm water).\n'
          'Be sure to RINSE AFTER EACH MEAL OR SNACK! If you keep your surgical site clean,\n'
          'you will heal, if you do not, it will cause secondary infection. Remember, it takes\n'
          'only one time for food to get into the surgical site and then secondary infection will\n'
          'start, so be sure to RINSE AFTER EACH MEAL OR SNACK!\n'
          '- BLEEDING: When you leave the office, you might be biting on a gauze pad to control\n'
          'bleeding. Keep slight pressure on this gauze for at least 30 to 60 minutes. Don’t\n'
          'change it during this time; it needs to remain undisturbed while a clot forms in the\n'
          'extraction socket. After 30 minutes you may remove it. You may bite on another\n'
          'gauze or a tea bag for another 30 minutes if you feel it is still bleeding. Small\n'
          'amounts of blood in the saliva can make your saliva appear quite red. This is normal\n'
          'and may be noticed the rest of the day after the procedure.\n'
          '- DIET: Eat soft foods until the area is healed. Maintain a good, balanced diet, you\n'
          'need proper nutrition to heal. Drink plenty of water. Avoid alcohol for 48\n'
          'hours. Keeping the area clean from food debris will promote good healing.\n'
          '- SMOKING: Smoking should be stopped following surgery. Healing and success of\n'
          'the surgery will be substantially reduced by the cigarette smoke chemicals in your\n'
          'body. Also the suction created when inhaling cigarettes can dislodge the clot.\n'
          'Smokers are at greater risk of developing a painful condition called “Dry Socket”,\n'
          'which can hurt worse then a toothache and there is no cure for it. You must quit for\n'
          'at least 5 day to allow initial healing.\n'
          '- PAIN: Some discomfort is normal after surgery. To minimize pain, take Tylenol,\n'
          'Motrin or Advil, or similar non-aspirin pain reliever to maintain comfort. Start take '
          'it\n'
          'before the anesthesia wears off. If prescription pain medication is prescribed, take '
          'it\n'
          'as instructed on the label. Don’t exceed the dose on the label. Taking with food or\n'
          'milk will help reduce upset stomach. Avoid driving or operating heavy machinery\n'
          'when taking pain prescriptions. Do not drink alcohol while taking prescription pain\n'
          'medications. Strong pain medications, like Norco, must be only taken before\n'
          'bedtime.\n'
          '- NAUSEA: This is most often caused by taking pain medications on an empty\n'
          'stomach. Reduce nausea by preceding each pain pill with soft food, and taking the\n'
          'pill with a large glass of water.\n'
          '- SWELLING: Applying an ice bag to the face over the operated area will minimize\n'
          'swelling. Apply for 15 minutes, then remove for 15 minutes. Continue this for the\n'
          'first day.\n'
          '- NUMBNESS: The local anesthetic will cause you to be numb for several hours after\n'
          'you leave the office. Be very careful not to bite, chew, pinch, or scratch the numb\n'
          'area. Sometimes the extraction causes residual numbness or tingling for six weeks\n'
          'or longer. Contact our office if you experience these symptoms.\n'
          '- BRUSHING: Do not brush your teeth for the first 8 hours after surgery. After this, '
          'you\n'
          'must brush your teeth to reduce bacteria amount, but avoid the area of surgery for\n'
          'few days.\n'
          '- RINSING: Avoid all rinsing or swishing for 24 hours after extraction. Rinsing can\n'
          'disturb the formation of a healing blood clot which is essential to proper healing.\n'
          'This could cause bleeding and risk of dry socket. After 24 hours you may begin\n'
          'gentle rinsing with a saltwater solution (1 or 2 teaspoon salt + 8 ounces warm water)\n'
          'after each meal or snack. Avoid commercial mouth rinses that contain alcohol.\n'
          '- ACTIVITY: After leaving the office, rest and avoid strenuous activities for the\n'
          'remainder of the day. Keeping blood pressure lower will reduce bleeding and aid\n'
          'healing.\n'
          '- ANTIBIOTICS: If you were given an antibiotic prescription, take all of them as\n'
          'directed until they are gone. Women: some antibiotics can reduce the effectiveness\n'
          'of birth control pills. Use alternate birth control methods for two months.\n'
          '- SINUS: If your sinus was involved in the procedure, you should avoid blowing your\n'
          'nose or playing a wind musical instrument for one week. Use of decongestant\n'
          'medications might be recommended.\n'
          '- SUTURES: If you had resorbable sutures placed, then they will dissolve on its own\n'
          'in 7-10 days and you do not need to worry about suture removal.\n'
          '- SPECIAL CONSIDERATIONS – Trismus (stiffness) in the face muscles may cause\n'
          'difficulty in opening your mouth for a period of days. Moist heat compresses can\n'
          'minimize this condition. You may experience aching from other teeth. This\n'
          'discomfort is caused by referred pain and is a temporary condition. It is not unusual\n'
          'to develop bruising in the area of the extraction. There may be a slight elevation in\n'
          'temperature for 24-48 hours. If the fever persists, please contact our office.\n'
          '- FOLLOW-UP APPOINTMENTS: You may need to return to the office for a brief\n'
          'follow-up healing check.\n'
          'Following these instructions very closely will greatly help your comfort, and promote\n'
          'uneventful healing of the area. If any of the instructions are not followed, you might '
          'have\n'
          'significantly more discomfort, and the success of the procedure may be affected.'},
 {'document_id': 'D10',
  'title': 'Crown Lengthening Post-Operative Instructions',
  'doc_type': 'crown_lengthening',
  'effective_date': '2025-02-15',
  'is_current': True,
  'text': 'CROWN LENGTHENING\n'
          '- MOST IMPORTANT DIRECTION: You have been given an IRRIGATION SYRINGE and\n'
          'instructed how and when to use it. You may begin gentle rinsing with IRRIGATION\n'
          'SYRINGE using a saltwater solution (1 or 2 teaspoon salt + 8 ounces warm water).\n'
          'Be sure to RINSE AFTER EACH MEAL OR SNACK! If you keep your surgical site clean,\n'
          'you will heal, if you do not, it will cause secondary infection. Remember, it takes\n'
          'only one time for food to get into the surgical site and then secondary infection will\n'
          'start, so be sure to RINSE AFTER EACH MEAL OR SNACK!\n'
          '- CHLORHEXIDINE RINSING: In addition to warm salt water rinses after each meal\n'
          'or every 2-3 hours, you would also need to rinse with “liquid antibiotic” called\n'
          'Chlorhexidine. If you been given prescription at your appointment, then follow these\n'
          'instructions. After breakfast and dinner, or morning and evening, when you rinse\n'
          'with warm salt water and get the site cleaned, now you need to rinse with\n'
          'Chlorhexidine, use same syringe and do exactly the same step as with warm salt\n'
          'water, but now use Chlorhexidine.\n'
          '- DO NOT: Swish, suck through a straw, spit or smoke, it can all dislodge the clot.\n'
          'Keep anything sharp from entering the wound (crunchy food, toothpicks, eating\n'
          'utensils). Be sure to chew on the opposite side until the area heals\n'
          'completely. Understand that any food caught inside the extraction socket (place\n'
          'where tooth used to be) can cause infection, pain and additional surgery, so stay on\n'
          'soft or liquid food diet and give your body enough time to heal, BUT BE SURE TO\n'
          'RINSE AFTER EACH MEAL OR SNACK!\n'
          '- BLEEDING: When you leave the office, you might be biting on a gauze pad to control\n'
          'bleeding. Keep slight pressure on this gauze for at least 30 to 60 minutes. Don’t\n'
          'change it during this time; it needs to remain undisturbed while a clot forms in the\n'
          'extraction socket. After 30 minutes you may remove it. You may bite on another\n'
          'gauze or a tea bag for another 30 minutes if you feel it is still bleeding. Small\n'
          'amounts of blood in the saliva can make your saliva appear quite red. This is normal\n'
          'and may be noticed the rest of the day after the procedure.\n'
          '- DIET: Eat soft foods until the area is healed. Maintain a good, balanced diet, you\n'
          'need proper nutrition to heal. Drink plenty of water. Avoid alcohol for 48\n'
          'hours. Keeping the area clean from food debris will promote good healing.\n'
          '- SMOKING: Smoking should be stopped following surgery. Healing and success of\n'
          'the surgery will be substantially reduced by the cigarette smoke chemicals in your\n'
          'body. Also the suction created when inhaling cigarettes can dislodge the clot.\n'
          'Smokers are at greater risk of developing a painful condition called “Dry Socket”,\n'
          'which can hurt worse then a toothache and there is no cure for it. You must quit for\n'
          'at least 5 day to allow initial healing.\n'
          '- PAIN: Some discomfort is normal after surgery. To minimize pain, take Tylenol,\n'
          'Motrin or Advil, or similar non-aspirin pain reliever to maintain comfort. Start take '
          'it\n'
          'before the anesthesia wears off. If prescription pain medication is prescribed, take '
          'it\n'
          'as instructed on the label. Don’t exceed the dose on the label. Taking it with food\n'
          'will help reduce upset stomach. Avoid driving or operating heavy machinery when\n'
          'taking pain prescriptions. Do not drink alcohol while taking prescription pain\n'
          'medications. Strong pain medications, like Norco, must be only taken before\n'
          'bedtime.\n'
          '- NAUSEA: This is most often caused by taking pain medications on an empty\n'
          'stomach. Reduce nausea by preceding each pain pill with soft food, and taking the\n'
          'pill with a large glass of water.\n'
          '- SWELLING: Applying an ice bag to the face over the operated area will minimize\n'
          'swelling. Apply for 15 minutes, then remove for 15 minutes. Continue this for the\n'
          'first day.\n'
          '- NUMBNESS: The local anesthetic will cause you to be numb for several hours after\n'
          'you leave the office. Be very careful not to bite, chew, pinch, or scratch the numb\n'
          'area. Sometimes the extraction causes residual numbness or tingling for six weeks\n'
          'or longer. Contact our office if you experience these symptoms.\n'
          '- BRUSHING: Do not brush your teeth for the first 8 hours after surgery. After this, '
          'you\n'
          'must brush your teeth to reduce bacteria amount, but avoid the area of surgery for\n'
          'few days.\n'
          '- ACTIVITY: After leaving the office, rest and avoid strenuous activities for the\n'
          'remainder of the day. Keeping blood pressure lower will reduce bleeding and aid\n'
          'healing.\n'
          '- ANTIBIOTICS: If you were given an antibiotic prescription, take all of them as\n'
          'directed until they are gone. Women: some antibiotics can reduce the effectiveness\n'
          'of birth control pills. Use alternate birth control methods for two months.\n'
          '- SINUS: If your sinus was involved in the procedure, you should avoid blowing your\n'
          'nose or playing a wind musical instrument for one week. Use of decongestant\n'
          'medications might be recommended.\n'
          '- SUTURES: If you had resorbable sutures placed, then they will dissolve on its own\n'
          'in 7-10 days and you do not need to worry about suture removal. If you have sutures\n'
          'that do not resorb, then you need to return back to the office for a sutures removal.\n'
          '- SPECIAL CONSIDERATIONS – Trismus (stiffness) in the face muscles may cause\n'
          'difficulty in opening your mouth for a period of days. Moist heat compresses can\n'
          'minimize this condition. You may experience aching from other teeth. This\n'
          'discomfort is caused by referred pain and is a temporary condition. It is not unusual\n'
          'to develop bruising in the area of the extraction. There may be a slight elevation in\n'
          'temperature for 24-48 hours. If the fever persists, please contact our office.\n'
          '- FOLLOW-UP APPOINTMENTS: You WILL NEED TO RETURN to the office for a brief\n'
          'follow-up healing check. We want to make sure you get checks and evaluated and\n'
          'staying on proper healing course. You WILL NEED TO RETURN in 6-8 weeks to work\n'
          'on your definitive crown, remember that the crown you are wearing now is\n'
          'temporary only, if it does come off or break, you need to report to us so that we can\n'
          'get your crown back on to prevent for your tooth to decay and fail, so that you do not\n'
          'lose that tooth.\n'
          'Following these instructions very closely will greatly help your comfort, and promote\n'
          'uneventful healing of the area. If any of the instructions are not followed, you might '
          'have\n'
          'significantly more discomfort, and the success of the procedure may be affected.'},
 {'document_id': 'D11',
  'title': 'Dental Implant Placement Post-Operative Instructions',
  'doc_type': 'implant_placement',
  'effective_date': '2025-03-15',
  'is_current': True,
  'text': 'DENTAL IMPLANT PLACEMENT\n'
          '- DO NOT DISTURB THE AREA: For the next few days, and especially the first\n'
          '24 hours, it is very important to allow your body to form a good clot and start\n'
          'natural healing process.\n'
          '- DO NOT: Swish, suck through a straw, spit or smoke, it can all dislodge the\n'
          'clot. Keep anything sharp from entering the wound (crunchy food,\n'
          'toothpicks, eating utensils).\n'
          '- Be sure to chew on the opposite side until the area heals completely.\n'
          '- Understand that any food caught inside the extraction socket (place where\n'
          'tooth used to be) can cause infection, pain and additional surgery, so stay on\n'
          'soft or liquid food diet and give your body enough time to heal.\n'
          '- MOST IMPORTANT DIRECTION: You have been given an IRRIGATION\n'
          'SYRINGE and instructed how and when to use it. You may begin gentle\n'
          'rinsing with IRRIGATION SYRINGE using a saltwater solution (1 or 2 teaspoon\n'
          'salt + 8 ounces warm water). Be sure to RINSE AFTER EACH MEAL OR\n'
          'SNACK! If you keep your surgical site clean, you will heal, if you do not, it will\n'
          'cause secondary infection. Remember, it takes only one time for food to get\n'
          'into the surgical site and then secondary infection will start, so be sure to\n'
          'RINSE AFTER EACH MEAL OR SNACK!\n'
          '- BLEEDING: When you leave the office, you might be biting on a gauze pad to\n'
          'control bleeding. Keep slight pressure on this gauze for at least 30 to 60\n'
          'minutes. Don’t change it during this time; it needs to remain undisturbed\n'
          'while a clot forms in the extraction socket. After 30 minutes you may remove\n'
          'it. You may bite on another gauze or a tea bag for another 30 minutes if you\n'
          'feel it is still bleeding. Small amounts of blood in the saliva can make your\n'
          'saliva appear quite red. This is normal and may be noticed the rest of the day\n'
          'after the procedure.\n'
          '- DIET: Eat soft foods until the area is healed. Maintain a good, balanced diet,\n'
          'you need proper nutrition to heal. Drink plenty of water. Avoid alcohol for 48\n'
          'hours. Keeping the area clean from food debris will promote good healing.\n'
          '- SMOKING: Smoking should be stopped following surgery. Healing and\n'
          'success of the surgery will be substantially reduced by the cigarette smoke\n'
          'chemicals in your body. Also the suction created when inhaling cigarettes\n'
          'can dislodge the clot. Smokers are at greater risk of developing a painful\n'
          'condition called “Dry Socket”, which can hurt worse then a toothache and\n'
          'there is no cure for it. You must quit for at least 5 day to allow initial healing.\n'
          '- PAIN: Some discomfort is normal after surgery. To minimize pain, take\n'
          'Tylenol, Motrin or Advil, or similar non-aspirin pain reliever to maintain\n'
          'comfort. Start take it before the anesthesia wears off. If prescription pain\n'
          'medication is prescribed, take it as instructed on the label. Don’t exceed the\n'
          'dose on the label. Taking with food will help reduce upset stomach. Avoid\n'
          'driving or operating heavy machinery when taking pain prescriptions. Do not\n'
          'drink alcohol while taking prescription pain medications. Strong pain\n'
          'medications, like Norco, must be only taken before bedtime.\n'
          '- NAUSEA: This is most often caused by taking pain medications on an empty\n'
          'stomach. Reduce nausea by preceding each pain pill with soft food, and\n'
          'taking the pill with a large glass of water.\n'
          '- SWELLING: Applying an ice bag to the face over the operated area will\n'
          'minimize swelling. Apply for 15 minutes, then remove for 15 minutes.\n'
          'Continue this for the first day.\n'
          '- NUMBNESS: The local anesthetic will cause you to be numb for several\n'
          'hours after you leave the office. Be very careful not to bite, chew, pinch, or\n'
          'scratch the numb area. Sometimes the extraction causes residual numbness\n'
          'or tingling for six weeks or longer. Contact our office if you experience these\n'
          'symptoms.\n'
          '- BRUSHING: Do not brush your teeth for the first 8 hours after surgery. After\n'
          'this, you must brush your teeth to reduce bacteria amount, but avoid the\n'
          'area of surgery for few days.\n'
          '- RINSING: Avoid all rinsing or swishing for 24 hours after extraction. Rinsing\n'
          'can disturb the formation of a healing blood clot which is essential to proper\n'
          'healing. This could cause bleeding and risk of dry socket. After 24 hours you\n'
          'may begin gentle rinsing with a saltwater solution (1 or 2 teaspoon salt + 8\n'
          'ounces warm water) after each meal or snack. Avoid commercial mouth\n'
          'rinses that contain alcohol.\n'
          '- ACTIVITY: After leaving the office, rest and avoid strenuous activities for the\n'
          'remainder of the day. Keeping blood pressure lower will reduce bleeding and\n'
          'aid healing.\n'
          '- ANTIBIOTICS: If you were given an antibiotic prescription, take all of them as\n'
          'directed until they are gone. Women: some antibiotics can reduce the\n'
          'effectiveness of birth control pills. Use alternate birth control methods for\n'
          'two months.\n'
          '- SINUS: If your sinus was involved in the procedure, you should avoid blowing\n'
          'your nose or playing a wind musical instrument for one week. Use of\n'
          'decongestant medications might be recommended.\n'
          '- SUTURES: If you had resorbable sutures placed, then they will dissolve on\n'
          'its own in 7-10 days and you do not need to worry about suture removal.\n'
          '- SPECIAL CONSIDERATIONS – Trismus (stiffness) in the face muscles may\n'
          'cause difficulty in opening your mouth for a period of days. Moist heat\n'
          'compresses can minimize this condition. You may experience aching from\n'
          'other teeth. This discomfort is caused by referred pain and is a temporary\n'
          'condition. It is not unusual to develop bruising in the area of the extraction.\n'
          'There may be a slight elevation in temperature for 24-48 hours. If the fever\n'
          'persists, please contact our office.\n'
          '- FOLLOW-UP APPOINTMENTS: You may need to return to the office for a\n'
          'brief follow-up healing check.\n'
          'Following these instructions very closely will greatly help your comfort, and promote\n'
          'uneventful healing of the area. If any of the instructions are not followed, you might '
          'have\n'
          'significantly more discomfort, and the success of the procedure may be affected.'},
 {'document_id': 'D12',
  'title': 'Deep Cleaning (Scaling and Root Planing) Post-Treatment Instructions',
  'doc_type': 'periodontal_scaling',
  'effective_date': '2025-06-01',
  'is_current': True,
  'text': 'DEEP CLEANING (Scaling and Root Planing)\n'
          'To minimize the discomfort and encourage proper healing following your scaling and '
          'root\n'
          'planing, follow these instructions:\n'
          '- After the procedure, take aspirin, acetaminophen (Tylenol®), or ibuprofen (Advil®)\n'
          'before the anesthetic wears off. Continue to take over the counter pain medication\n'
          'for the next two days even if you do not have any discomfort.\n'
          '- A saltwater solution (1 OR 2 teaspoon salt + 8 ounces warm water) swished in your\n'
          'mouth for 2 to 3 minutes every hour may make your mouth more comfortable.\n'
          '- Use a soft toothbrush and floss at least two times a day. Be gentle and clean\n'
          'thoroughly. Plaque (Bacteria) will start to grow and removing it with brushing and\n'
          'flossing at least twice a day will promote a positive outcome of the treatment.\n'
          '- Slight bleeding may occur while brushing as the tissues begin to heal and is normal\n'
          'up to 4 weeks following treatment.\n'
          '- Avoid strong spicy seasonings, and hard crunchy foods for the next few days.\n'
          '- Smoking should be stopped. Success of the treatment will be substantially reduced\n'
          'by the cigarette smoke chemicals in your body.\n'
          '- As the tissues heal, some temporary sensitivity to cold may occur. Use a\n'
          'desensitizing toothpaste (such as Sensodyne® without whitening), or fluoride gel\n'
          '(such as Prevident® or Gel-Kam®) frequently (at least 4 times/day) for 1 to 2 weeks.\n'
          'Also, the cleaner the teeth are kept, the less sensitive they will be.\n'
          '- Faithfully use any other oral hygiene aids that have been recommended (floss,\n'
          'waterpick, chlorhexidine, rubber tip, Sonicare®, Proxabrush®, Peridex® mouthrinse,\n'
          'etc).\n'
          '- If you had antibiotics like Arestin or Atridox applied at the time of deep cleaning, '
          'do\n'
          'all the recommended post op instructions but DO NOT floss or waterpick the\n'
          'treated teeth with antibiotics for at least 10 days.\n'
          '- Always Follow Up. Because the bacteria that cause periodontal disease are\n'
          'persistent, the infection can return. Please be sure to make follow-\n'
          'up appointments with your dental professional to maintain healthy gums and\n'
          'teeth.\n'
          '- Keep Your Scheduled Appointments. It is important to keep all of your dental\n'
          'appointments so that your dental professional can re-examine your gums,\n'
          'make sure the infection is under control, and measure the success of your\n'
          'treatment.'},
 {'document_id': 'D13',
  'title': 'Gum Graft Post-Operative Instructions',
  'doc_type': 'gum_graft',
  'effective_date': '2025-04-20',
  'is_current': True,
  'text': 'GUM GRAFT\n'
          '- MOST IMPORTANT DIRECTION: You have been given an IRRIGATION\n'
          'SYRINGE and instructed how and when to use it. You may begin gentle\n'
          'rinsing with IRRIGATION SYRINGE using a saltwater solution (1 or 2\n'
          'teaspoon salt + 8 ounces warm water). Be sure to RINSE AFTER EACH\n'
          'MEAL OR SNACK! If you keep your surgical site clean, you will heal, if\n'
          'you do not, it will cause secondary infection. Remember, it takes only\n'
          'one time for food to get into the surgical site and then secondary\n'
          'infection will start, so be sure to RINSE AFTER EACH MEAL OR\n'
          'SNACK!\n'
          '- CHLORHEXIDINE RINSING: In addition to warm salt water rinses\n'
          'after each meal or every 2-3 hours, you would also need to rinse with\n'
          '“liquid antibiotic” called Chlorhexidine. If you been given prescription\n'
          'at your appointment, then follow these instructions. After breakfast\n'
          'and dinner, or morning and evening, when you rinse with warm salt\n'
          'water and get the site cleaned, now you need to rinse with\n'
          'Chlorhexidine, use same syringe and do exactly the same step as with\n'
          'warm salt water, but now use Chlorhexidine.\n'
          '- STENT/MATRIX: If you being given a clear matrix/stent for your upper jaw to\n'
          'cover the donor site on the roof of your mouth, you may wear it for all the\n'
          'time or during the day, depends on how much discomfort you feel. Take the\n'
          'stent out after each time you each and rinse it under luke warm water, use\n'
          'toothbrush and soap to clean it, do not use toothpaste. Everytime you rinse,\n'
          'take the matrix out and make sure the solution gets to the wound. Do not put\n'
          'matrix into the hot water.\n'
          '- DO NOT: Swish, suck through a straw, spit or smoke, it can all dislodge the\n'
          'clot. Keep anything sharp from entering the wound (crunchy food,\n'
          'toothpicks, eating utensils). Be sure to chew on the opposite side until the\n'
          'area heals completely. Understand that any food caught inside the\n'
          'extraction socket (place where tooth used to be) can cause infection, pain\n'
          'and additional surgery, so stay on soft or liquid food diet and give your body\n'
          'enough time to heal, BUT BE SURE TO RINSE AFTER EACH MEAL OR SNACK!\n'
          '- BLEEDING: When you leave the office, you might be biting on a gauze pad to\n'
          'control bleeding. Keep slight pressure on this gauze for at least 30 to 60\n'
          'minutes. Don’t change it during this time; it needs to remain undisturbed\n'
          'while a clot forms in the extraction socket. After 30 minutes you may remove\n'
          'it. You may bite on another gauze or a tea bag for another 30 minutes if you\n'
          'feel it is still bleeding. Small amounts of blood in the saliva can make your\n'
          'saliva appear quite red. This is normal and may be noticed the rest of the day\n'
          'after the procedure.\n'
          '- DIET: Eat soft foods until the area is healed. Maintain a good, balanced diet,\n'
          'you need proper nutrition to heal. Drink plenty of water. Avoid alcohol for 48\n'
          'hours. Keeping the area clean from food debris will promote good healing.\n'
          '- SMOKING: Smoking should be stopped following surgery. Healing and\n'
          'success of the surgery will be substantially reduced by the cigarette smoke\n'
          'chemicals in your body. Also the suction created when inhaling cigarettes\n'
          'can dislodge the clot. Smokers are at greater risk of developing a painful\n'
          'condition called “Dry Socket”, which can hurt worse then a toothache and\n'
          'there is no cure for it. You must quit for at least 5 day to allow initial healing.\n'
          '- PAIN: Some discomfort is normal after surgery. To minimize pain, take\n'
          'Tylenol, Motrin or Advil, or similar non-aspirin pain reliever to maintain\n'
          'comfort. Start take it before the anesthesia wears off. If prescription pain\n'
          'medication is prescribed, take it as instructed on the label. Don’t exceed the\n'
          'dose on the label. Taking it with food will help reduce upset stomach. Avoid\n'
          'driving or operating heavy machinery when taking pain prescriptions. Do not\n'
          'drink alcohol while taking prescription pain medications. Strong pain\n'
          'medications, like Norco, must be only taken before bedtime.\n'
          '- NAUSEA: This is most often caused by taking pain medications on an empty\n'
          'stomach. Reduce nausea by preceding each pain pill with soft food, and\n'
          'taking the pill with a large glass of water.\n'
          '- SWELLING: Applying an ice bag to the face over the operated area will\n'
          'minimize swelling. Apply for 15 minutes, then remove for 15 minutes.\n'
          'Continue this for the first day.\n'
          '- NUMBNESS: The local anesthetic will cause you to be numb for several\n'
          'hours after you leave the office. Be very careful not to bite, chew, pinch, or\n'
          'scratch the numb area. Sometimes the extraction causes residual numbness\n'
          'or tingling for six weeks or longer. Contact our office if you experience these\n'
          'symptoms.\n'
          '- BRUSHING: Do not brush your teeth for the first 8 hours after surgery. After\n'
          'this, you must brush your teeth to reduce bacteria amount, but avoid the\n'
          'area of surgery for few days.\n'
          '- ACTIVITY: After leaving the office, rest and avoid strenuous activities for the\n'
          'remainder of the day. Keeping blood pressure lower will reduce bleeding and\n'
          'aid healing.\n'
          '- ANTIBIOTICS: If you were given an antibiotic prescription, take all of them as\n'
          'directed until they are gone. Women: some antibiotics can reduce the\n'
          'effectiveness of birth control pills. Use alternate birth control methods for\n'
          'two months.\n'
          '- SINUS: If your sinus was involved in the procedure, you should avoid blowing\n'
          'your nose or playing a wind musical instrument for one week. Use of\n'
          'decongestant medications might be recommended.\n'
          '- SUTURES: If you had resorbable sutures placed, then they will dissolve on\n'
          'its own in 7-10 days and you do not need to worry about suture removal. If\n'
          'you have sutures that do not resorb, then you need to return back to the\n'
          'office for a sutures removal.\n'
          '- SPECIAL CONSIDERATIONS – Trismus (stiffness) in the face muscles may\n'
          'cause difficulty in opening your mouth for a period of days. Moist heat\n'
          'compresses can minimize this condition. You may experience aching from\n'
          'other teeth. This discomfort is caused by referred pain and is a temporary\n'
          'condition. It is not unusual to develop bruising in the area of the extraction.\n'
          'There may be a slight elevation in temperature for 24-48 hours. If the fever\n'
          'persists, please contact our office.\n'
          '- FOLLOW-UP APPOINTMENTS: You may need to return to the office for a\n'
          'brief follow-up healing check.\n'
          'Following these instructions very closely will greatly help your comfort, and promote\n'
          'uneventful healing of the area. If any of the instructions are not followed, you might '
          'have\n'
          'significantly more discomfort, and the success of the procedure may be affected.'},
 {'document_id': 'D14',
  'title': 'Invisalign Clear Aligner Care Instructions',
  'doc_type': 'clear_aligner_care',
  'effective_date': '2025-05-15',
  'is_current': True,
  'text': 'INVISALIGN BRACES CARE\n'
          '- Taking care of Invisalign clear aligners is very simple. Every time you brush your\n'
          'teeth you can brush your aligners but without a toothpaste. The best way to clean\n'
          'your aligners is to use the Invisalign cleaning kit. They can also be soaked and\n'
          'cleaned in a denture cleaner.\n'
          '- It is not advisable to remove your aligners at night.\n'
          '- Thanks to the removable nature though, you can eat and drink whatever you want\n'
          'while in treatment. In fact, you’re required to remove your aligners to eat and drink.\n'
          'So, unlike undergoing traditional treatment using wires and brackets, there is no\n'
          'need to restrict your consumption of any of your favorite foods and snacks unless\n'
          'instructed otherwise by Dr. Denisovich.\n'
          '- Also, it is important that you brush your teeth after each meal and prior to re-\n'
          'inserting your aligners to maintain fresh breath and proper hygiene.\n'
          '- Dr. Denisovich discourages smoking while wearing aligners because it is possible\n'
          'for the aligners to become discolored.\n'
          '- You cannot chew gum while wearing your aligners. It will stick to the aligners.\n'
          '- We recommend removing your aligners for all meals and snacks.\n'
          'Trays May Cause Some Irritation To The Lips, Tongue, And Cheeks\n'
          'If This Occurs\n'
          '- Use wax to stop the irritation\n'
          '- Rinse with warm salt water to help irritation heal\n'
          '- Products like Zilactin-B or a peroxide based rinse can be helpful, and are available\n'
          'over the counter\n'
          'Things TO DO During Invisalign Treatment:\n'
          '- Wear each set of trays for at least 2 weeks, unless otherwise instructed\n'
          '- Wear each set of trays for 18- 20 hours a day, unless otherwise instructed\n'
          '- Use denture cleaner tablets to clean trays at least once a day\n'
          '- Always place trays in case when not in your mouth\n'
          '- Always remove trays by starting from the back molars\n'
          '- Always place trays in from the front of your mouth first, and then move to the back\n'
          'teeth\n'
          '- You may drink water while wearing trays or use a straw for dark liquids\n'
          '- If possible, brush or rinse before placing trays back in your mouth\n'
          '- Clenching into trays w/ your aligner chewies during the first 2-3 days helps teeth\n'
          'move faster and relieve pressure. Only clench for 30-40 sec each quadrant, and\n'
          'repeat for 5-10 min, but only do this if you have no history of jaw problems\n'
          '- Wear trays as instructed in sequential order\n'
          '- Keep 2 to 3 of your previous trays in a clean plastic bag\n'
          'Things NOT TO DO During Invisalign Treatment:\n'
          '- Throw away trays\n'
          '- Leave trays out of mouth for long periods of time\n'
          '- Chew gum with aligners in your mouth\n'
          '- Leave trays in hot vehicle, or boil them (They are plastic!)\n'
          '- Leave trays sitting out for pets or small children to chew on\n'
          '- Wrap trays in a napkin (You will throw them away acidently!)\n'
          '- Place trays in your pocket without a case\n'
          '- Have dental work done while in treatment, EXCEPT for regular checkups and\n'
          'cleanings\n'
          '- Eat while wearing trays\n'
          '- Remove trays from the front teeth first\n'
          '- Drink dark teas, coffee or soda with trays in (Use a straw)\n'
          '- Set trays on table at a restaurant\n'
          '- Bite trays into position, this may damage them\n'
          '- Use mouthwash or toothpaste on trays\n'
          'Teeth may begin to feel slightly mobile or loose during treatment, but this is normal.\n'
          'Non-compliant wear of aligners may result in the need for new impressions and '
          'additional\n'
          'fees'},
 {'document_id': 'D15',
  'title': 'Post-Operative Care After a Dental Night Guard',
  'doc_type': 'night_guard_care',
  'effective_date': '2025-06-15',
  'is_current': True,
  'text': 'Post-Operative Care After a Dental Night Guard\n'
          'When traveling, store your Night Guard in a clean, dry place. A hard case is ideal for\n'
          'protecting your night guard from damage and dust. You can simply use dental pod '
          'tablets\n'
          'and dissolve them in a cup of water to soak your night guard during the day when the '
          'actual\n'
          'dental pod ultrasonic cleaner is not available.\n'
          'Bring your night guard to all dental appointments. We will need to check it for wear '
          'and tear\n'
          'and make sure it is still fitting properly.\n'
          'Wearing Your Night Guard:\n'
          'Wear your night guard as directed by your dentist. This is usually every night while '
          'you\n'
          'sleep. REMEMBER - It only works when you wear it.\n'
          'Do not chew on your night guard. This can cause it to break or become misshapen.\n'
          'Do not let your lovely dog or a cat find it, if they do, then this would be the last '
          'time you will\n'
          'see it.\n'
          'If your night guard feels uncomfortable, contact us. You may need adjustments for a '
          'better\n'
          'fit.\n'
          'Additional Tips:\n'
          'You may experience some minor discomfort when you first start wearing your night '
          'guard.\n'
          'This is normal and should subside within a few weeks.\n'
          'You may also experience increased saliva production while wearing your night guard. '
          'This\n'
          'is also normal and should subside over time.\n'
          'By following these post-operative care instructions, you can help ensure that your '
          'night\n'
          'guard is effective and lasts for many years.\n'
          'Please note: These are general post-operative care instructions. It is important to '
          'follow the\n'
          'specific instructions provided to you at your visit.\n'
          'Over time, night guards can wear down and lose their effectiveness.'},
 {'document_id': 'D16',
  'title': 'Partial or Complete Denture Care Instructions',
  'doc_type': 'denture_care',
  'effective_date': '2025-07-01',
  'is_current': True,
  'text': 'PARTIAL OR COMPLETE DENTURE\n'
          '- New dentures always require a period of adjustment. First-time denture patients\n'
          'may require several weeks or months to get used to their new appliance. Speech\n'
          'may be altered, and may require adaptation of the tongue and lips.\n'
          '- For the first few days, you should wear your dentures for as long as possible, and\n'
          'chew soft food in small bites on both sides of your mouth. Remember, dentures do\n'
          'not have the same chewing efficiency as natural teeth and may affect your taste of\n'
          'food.\n'
          '- If your bite feels uneven after several days, please let us know, we can adjust the\n'
          'way your teeth contact at follow-up visits.\n'
          '- It is not unusual for sore spots to develop in isolated areas of the mouth. These\n'
          'areas can be relieved easily at follow-up appointments.\n'
          '- If a severe sore spot develops which prevents wearing the denture and an\n'
          'appointment is made for adjustment, please wear the denture for 24 hours prior to\n'
          'the appointment. This will greatly aid in locating the exact area, and make\n'
          'adjustments significantly easier and more predictable.\n'
          '- Proper cleaning of your denture is important to prevent stains and bacteria from\n'
          'accumulating on your appliance. Since cleaning procedures differ for various types\n'
          'of appliances, please follow the directions given to you at your insertion\n'
          'appointment.\n'
          '- DO NOT wear your complete or partial dentures to bed. It is important to allow your\n'
          'gum tissues and jaw bones to rest in order to prevent further tissue irritation,\n'
          'infection, and future bone shrinkage.\n'
          '- Over time, or with weight change, the supporting gum tissues and bone will change\n'
          'shape and size. Periodic relines of your dentures may be necessary to ensure a\n'
          'retentive fit. Denture teeth will wear or chip over time. For this reason, an annual\n'
          'check of your tissues and dentures is recommended.'},
 {'document_id': 'D17',
  'title': 'Tooth Extraction - General Dental Surgery Post-Operative Instructions',
  'doc_type': 'tooth_extraction_general',
  'effective_date': '2025-01-25',
  'is_current': True,
  'text': 'TOOTH EXTRACTION - GENERAL DENTAL SURGERY\n'
          '- MOST IMPORTANT DIRECTION: You have been given an IRRIGATION\n'
          'SYRINGE and instructed how and when to use it. You may begin gentle\n'
          'rinsing with IRRIGATION SYRINGE using a saltwater solution (1 or 2 teaspoon\n'
          'salt + 8 ounces warm water). Be sure to RINSE AFTER EACH MEAL OR\n'
          'SNACK! If you keep your surgical site clean, you will heal, if you do not, it will\n'
          'cause secondary infection. Remember, it takes only one time for food to get\n'
          'into the surgical site and then secondary infection will start, so be sure to\n'
          'RINSE AFTER EACH MEAL OR SNACK!\n'
          '- DO NOT DISTURB THE AREA: For the next few days, and especially the first\n'
          '24 hours, it is very important to allow your body to form a good clot and start\n'
          'natural healing process.\n'
          '- DO NOT: Swish, suck through a straw, spit or smoke, it can all dislodge the\n'
          'clot. Keep anything sharp from entering the wound (crunchy food,\n'
          'toothpicks, eating utensils). Be sure to chew on the opposite side until the\n'
          'area heals completely. Understand that any food caught inside the\n'
          'extraction socket (place where tooth used to be) can cause infection, pain\n'
          'and additional surgery, so stay on soft or liquid food diet and give your body\n'
          'enough time to heal, BUT BE SURE TO RINSE AFTER EACH MEAL OR SNACK!\n'
          '- BLEEDING: When you leave the office, you might be biting on a gauze pad to\n'
          'control bleeding. Keep slight pressure on this gauze for at least 30 to 60\n'
          'minutes. Don’t change it during this time; it needs to remain undisturbed\n'
          'while a clot forms in the extraction socket. After 30 minutes you may remove\n'
          'it. You may bite on another gauze or a tea bag for another 30 minutes if you\n'
          'feel it is still bleeding. Small amounts of blood in the saliva can make your\n'
          'saliva appear quite red. This is normal and may be noticed the rest of the day\n'
          'after the procedure.\n'
          '- DIET: Eat soft foods until the area is healed. Maintain a good, balanced diet,\n'
          'you need proper nutrition to heal. Drink plenty of water. Avoid alcohol for 48\n'
          'hours. Keeping the area clean from food debris will promote good healing.\n'
          '- SMOKING: Smoking should be stopped following surgery. Healing and\n'
          'success of the surgery will be substantially reduced by the cigarette smoke\n'
          'chemicals in your body. Also the suction created when inhaling cigarettes\n'
          'can dislodge the clot. Smokers are at greater risk of developing a painful\n'
          'condition called “Dry Socket”, which can hurt worse then a toothache and\n'
          'there is no cure for it. You must quit for at least 5 day to allow initial healing.\n'
          '- PAIN: Some discomfort is normal after surgery. To minimize pain, take\n'
          'Tylenol, Motrin or Advil, or similar non-aspirin pain reliever to maintain\n'
          'comfort. Start take it before the anesthesia wears off. If prescription pain\n'
          'medication is prescribed, take it as instructed on the label. Don’t exceed the\n'
          'dose on the label. Taking with food will help reduce upset stomach. Avoid\n'
          'driving or operating heavy machinery when taking pain prescriptions. Do not\n'
          'drink alcohol while taking prescription pain medications. Strong pain\n'
          'medications, like Norco, must be only taken before bedtime.\n'
          '- NAUSEA: This is most often caused by taking pain medications on an empty\n'
          'stomach. Reduce nausea by preceding each pain pill with soft food, and\n'
          'taking the pill with a large glass of water.\n'
          '- SWELLING: Applying an ice bag to the face over the operated area will\n'
          'minimize swelling. Apply for 15 minutes, then remove for 15 minutes.\n'
          'Continue this for the first day.\n'
          '- NUMBNESS: The local anesthetic will cause you to be numb for several\n'
          'hours after you leave the office. Be very careful not to bite, chew, pinch, or\n'
          'scratch the numb area. Sometimes the extraction causes residual numbness\n'
          'or tingling for six weeks or longer. Contact our office if you experience these\n'
          'symptoms.\n'
          '- BRUSHING: Do not brush your teeth for the first 8 hours after surgery. After\n'
          'this, you must brush your teeth to reduce bacteria amount, but avoid the\n'
          'area of surgery for few days.\n'
          '- RINSING: You may begin gentle rinsing with IRRIGATION SYRINGE using a\n'
          'saltwater solution (1 or 2 teaspoon salt + 8 ounces warm water). Be sure to\n'
          'RINSE AFTER EACH MEAL OR SNACK! If you keep your surgical site clean,\n'
          'you will heal, if you do not, it will cause secondary infection. Remember, it\n'
          'takes only one time for food to get into the surgical site and then secondary\n'
          'infection will start, so be sure to RINSE AFTER EACH MEAL OR SNACK! Avoid\n'
          'commercial mouth rinses that contain alcohol.\n'
          '- ACTIVITY: After leaving the office, rest and avoid strenuous activities for the\n'
          'remainder of the day. Keeping blood pressure lower will reduce bleeding and\n'
          'aid healing.\n'
          '- ANTIBIOTICS: If you were given an antibiotic prescription, take all of them as\n'
          'directed until they are gone. Women: some antibiotics can reduce the\n'
          'effectiveness of birth control pills. Use alternate birth control methods for\n'
          'two months.\n'
          '- SINUS: If your sinus was involved in the procedure, you should avoid blowing\n'
          'your nose or playing a wind musical instrument for one week. Use of\n'
          'decongestant medications might be recommended.\n'
          '- SUTURES: If you had resorbable sutures placed, then they will dissolve on\n'
          'its own in 7-10 days and you do not need to worry about suture removal. If\n'
          'you have sutures that do not resorb, then you need to return back to the\n'
          'office for a sutures removal.\n'
          '- SPECIAL CONSIDERATIONS – Trismus (stiffness) in the face muscles may\n'
          'cause difficulty in opening your mouth for a period of days. Moist heat\n'
          'compresses can minimize this condition. You may experience aching from\n'
          'other teeth. This discomfort is caused by referred pain and is a temporary\n'
          'condition. It is not unusual to develop bruising in the area of the extraction.\n'
          'There may be a slight elevation in temperature for 24-48 hours. If the fever\n'
          'persists, please contact our office.\n'
          '- FOLLOW-UP APPOINTMENTS: You may need to return to the office for a\n'
          'brief follow-up healing check.\n'
          'Following these instructions very closely will greatly help your comfort, and promote\n'
          'uneventful healing of the area. If any of the instructions are not followed, you might '
          'have\n'
          'significantly more discomfort, and the success of the procedure may be affected.'},
 {'document_id': 'D18',
  'title': 'White (Composite) Fillings Post-Operative Instructions',
  'doc_type': 'composite_fillings',
  'effective_date': '2025-02-25',
  'is_current': True,
  'text': 'WHITE FILLINGS\n'
          '- When anesthesia has been used, your lips, teeth, and tongue may be numb for\n'
          'several hours after the appointment. Avoid any chewing until the numbness has\n'
          'completely worn off. It is easy to bite or burn your tongue or lip while numb.\n'
          '- It is normal to experience some hot, cold and pressure sensitivity after your\n'
          'appointment. Your gums may be sore for several days.\n'
          '- Rinse your mouth three times a day with warm salt water (put a teaspoon of salt in a\n'
          'cup of warm water, rinse and spit) to reduce pain and swelling.\n'
          '- Your new composite fillings are fully hardened before you even leave the office and\n'
          'you can chew shortly after the numbing goes away!\n'
          '- One of the most common problems following filling placement with anesthesia, is\n'
          'an uneven bite. It is simply because its hard for the patient to feel correct bite due\n'
          'to numbness. Most of the time it resolves within few days by it self.\n'
          '- When decay is deep, a medication is placed under the filling to help preserve nerve\n'
          'vitality to avoid root canal. This procedure has very good success rate, but\n'
          'occasionally root canal might still be required.'},
 {'document_id': 'D19',
  'title': 'Take-Home Whitening Trays - General Instructions',
  'doc_type': 'whitening_take_home_general',
  'effective_date': '2025-03-25',
  'is_current': True,
  'text': 'WHITENING - TAKE HOME TRAYS\n'
          'While bleaching or whitening your teeth, normal oral hygiene measures should be '
          'followed\n'
          '(flossing and brushing).\n'
          '- Bead the bleaching gel inside your custom tray, using caution not to overload the\n'
          'tray. Insert the tray into your mouth over teeth and gently wipe any excess gel from\n'
          'around the edges of your tray, taking extra care not to leave any gel on your gums.\n'
          'Irritated gums usually means you have used too much gel in your tray.\n'
          '- Wear the tray for brief time, 30 minutes, to see how your mouth reacts to it. If you\n'
          'feel comfortable, then wear the trays as directed to you at your delivery\n'
          'appointment. The time of wear is based on the concentration and type of bleaching\n'
          'material utilized for your case. If the sensitivity is too uncomfortable, stop and\n'
          'reduce time and/or frequency. Usually sensitivity stops after several days.\n'
          '- While bleaching, do not rinse your mouth, since this may dilute the bleaching agent.\n'
          '- Do not swallow the whitening gel.\n'
          '- Never drink, eat, or smoke while wearing your tray.\n'
          '- Do not consume any red, black or staining foods like: coffee, sodas, red wine, etc.\n'
          '- After completing your bleaching session, remove the tray and gently clean it with a\n'
          'toothbrush and tap water without toothpaste. Rinse it completely, and let dry\n'
          'thoroughly before the next session.\n'
          'If you develop severe sensitivity or pain stop bleaching and please contact our office '
          'at\n'
          'your convenience.'}]


if __name__ == "__main__":
    outdated = [d['document_id'] for d in DOCUMENTS if not d['is_current']]
    print(f"Total documents: {len(DOCUMENTS)}")
    print(f"Outdated documents: {outdated}")
